version: '3.7'
services:
  todo-web-application:
    image: in28min/todo-web-application-mysql:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - mysql 
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: todos
      RDS_USERNAME: root
      RDS_PASSWORD: sa

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_ROOT_PASSWORD: sa 
      MYSQL_USER: root
      MYSQL_PASSWORD: sa
      MYSQL_DATABASE: todos
    volumes:
      - mysql-database-data-volume:/var/lib/mysql


volumes:
  mysql-database-data-volume:
