apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  #creationTimestamp: "2021-02-01T17:40:21Z"
  #generation: 1
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  #resourceVersion: "144225"
  #selfLink: /apis/apps/v1/namespaces/default/deployments/currency-exchange
  #uid: 21feeb4f-8387-4555-9e88-8a8672f5cfe1
spec:
  #progressDeadlineSeconds: 600
  replicas: 1
  #revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      #creationTimestamp: null
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: arafat1234/mmv2-currency-exchange-service:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv2-currency-exchange-service
        #resources: {}
        #terminationMessagePath: /dev/termination-log
        #terminationMessagePolicy: File
      #dnsPolicy: ClusterFirst
      restartPolicy: Always
      #schedulerName: default-scheduler
      #securityContext: {}
      #terminationGracePeriodSeconds: 30
#---      
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-02-01T17:40:37Z"
    lastUpdateTime: "2021-02-01T17:40:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-02-01T17:40:21Z"
    lastUpdateTime: "2021-02-01T17:40:37Z"
    message: ReplicaSet "currency-exchange-5fbf899489" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-02-01T17:40:21Z"
  generation: 1
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "144225"
  selfLink: /apis/apps/v1/namespaces/default/deployments/currency-exchange
  uid: 21feeb4f-8387-4555-9e88-8a8672f5cfe1
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: arafat1234/mmv2-currency-exchange-service:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv2-currency-exchange-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-02-01T17:40:37Z"
    lastUpdateTime: "2021-02-01T17:40:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-02-01T17:40:21Z"
    lastUpdateTime: "2021-02-01T17:40:37Z"
    message: ReplicaSet "currency-exchange-5fbf899489" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
# 
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-02-01T17:40:34Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "144407"
  selfLink: /api/v1/namespaces/default/services/currency-exchange
  uid: d1cfe1b6-119d-4f8e-8a47-929c76169531
spec:
  clusterIP: 10.44.5.187
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31821
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.122.43.185
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-02-01T17:40:21Z","generation":1,"labels":{"app":"currency-exchange"},"name":"currency-exchange","namespace":"default","resourceVersion":"144225","selfLink":"/apis/apps/v1/namespaces/default/deployments/currency-exchange","uid":"21feeb4f-8387-4555-9e88-8a8672f5cfe1"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"currency-exchange"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"currency-exchange"}},"spec":{"containers":[{"image":"arafat1234/mmv2-currency-exchange-service:0.0.11-SNAPSHOT","imagePullPolicy":"IfNotPresent","name":"mmv2-currency-exchange-service","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-02-01T17:40:37Z","lastUpdateTime":"2021-02-01T17:40:37Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-02-01T17:40:21Z","lastUpdateTime":"2021-02-01T17:40:37Z","message":"ReplicaSet \"currency-exchange-5fbf899489\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2021-02-01T17:40:21Z"
  generation: 2
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "163455"
  selfLink: /apis/apps/v1/namespaces/default/deployments/currency-exchange
  uid: 21feeb4f-8387-4555-9e88-8a8672f5cfe1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: arafat1234/mmv2-currency-exchange-service:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv2-currency-exchange-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-02-01T17:40:37Z"
    lastUpdateTime: "2021-02-01T17:40:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-02-01T17:40:21Z"
    lastUpdateTime: "2021-02-01T17:40:37Z"
    message: ReplicaSet "currency-exchange-5fbf899489" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/neg":"{\"ingress\":true}"},"creationTimestamp":"2021-02-01T17:40:34Z","finalizers":["service.kubernetes.io/load-balancer-cleanup"],"labels":{"app":"currency-exchange"},"name":"currency-exchange","namespace":"default","resourceVersion":"144407","selfLink":"/api/v1/namespaces/default/services/currency-exchange","uid":"d1cfe1b6-119d-4f8e-8a47-929c76169531"},"spec":{"clusterIP":"10.44.5.187","externalTrafficPolicy":"Cluster","ports":[{"nodePort":31821,"port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"currency-exchange"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"ip":"34.122.43.185"}]}}}
  creationTimestamp: "2021-02-01T17:40:34Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "163460"
  selfLink: /api/v1/namespaces/default/services/currency-exchange
  uid: d1cfe1b6-119d-4f8e-8a47-929c76169531
spec:
  clusterIP: 10.44.5.187
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31821
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.122.43.185
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-02-01T17:40:21Z","generation":1,"labels":{"app":"currency-exchange"},"name":"currency-exchange","namespace":"default","resourceVersion":"144225","selfLink":"/apis/apps/v1/namespaces/default/deployments/currency-exchange","uid":"21feeb4f-8387-4555-9e88-8a8672f5cfe1"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"currency-exchange"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"currency-exchange"}},"spec":{"containers":[{"image":"arafat1234/mmv2-currency-exchange-service:0.0.11-SNAPSHOT","imagePullPolicy":"IfNotPresent","name":"mmv2-currency-exchange-service","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-02-01T17:40:37Z","lastUpdateTime":"2021-02-01T17:40:37Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-02-01T17:40:21Z","lastUpdateTime":"2021-02-01T17:40:37Z","message":"ReplicaSet \"currency-exchange-5fbf899489\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2021-02-01T17:40:21Z"
  generation: 3
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "167282"
  selfLink: /apis/apps/v1/namespaces/default/deployments/currency-exchange
  uid: 21feeb4f-8387-4555-9e88-8a8672f5cfe1
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: arafat1234/mmv2-currency-exchange-service:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv2-currency-exchange-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-02-01T17:40:21Z"
    lastUpdateTime: "2021-02-01T17:40:37Z"
    message: ReplicaSet "currency-exchange-5fbf899489" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-02-01T18:45:10Z"
    lastUpdateTime: "2021-02-01T18:45:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/neg":"{\"ingress\":true}"},"creationTimestamp":"2021-02-01T17:40:34Z","finalizers":["service.kubernetes.io/load-balancer-cleanup"],"labels":{"app":"currency-exchange"},"name":"currency-exchange","namespace":"default","resourceVersion":"144407","selfLink":"/api/v1/namespaces/default/services/currency-exchange","uid":"d1cfe1b6-119d-4f8e-8a47-929c76169531"},"spec":{"clusterIP":"10.44.5.187","externalTrafficPolicy":"Cluster","ports":[{"nodePort":31821,"port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"currency-exchange"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"ip":"34.122.43.185"}]}}}
  creationTimestamp: "2021-02-01T17:40:34Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "163460"
  selfLink: /api/v1/namespaces/default/services/currency-exchange
  uid: d1cfe1b6-119d-4f8e-8a47-929c76169531
spec:
  clusterIP: 10.44.5.187
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31821
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.122.43.185
